### ISSUE TITLE
Compatiblity with IE11

### ISSUE THREAD

**Issue by CarlVerret** [Wikiki/bulma-quickview#13]
Hi,

I've successfuly used your nice component with Chrome but it doesn't work with IE11, stopping on the following lines:

`var onQuickviewShowClick = Symbol('onQuickviewShowClick');
var onQuickviewDismissClick = Symbol('onQuickviewDismissClick');`

Is there any workaround to make it working with IE11 just using the .js files in dist folder ? 

Thanks a lot.

**Comment by CarlVerret** [comment]
maybe a workaround :   trying to make things work, I've been able to use quickview with ie11 by changing this ;

`  var onQuickviewShowClick = 'onQuickviewShowClick'; // Symbol('onQuickviewShowClick');`
`  var onQuickviewDismissClick = 'onQuickviewDismissClick'; // Symbol('onQuickviewDismissClick');`

**Comment by Wikiki** [comment]
Hi,

as a workaround you can use the following babel polyfill:
```<script src="https://cdnjs.cloudflare.com/ajax/libs/babel-core/5.6.15/browser-polyfill.min.js"></script>```
