### ISSUE TITLE
bulmaQuickview is not defined

### ISSUE THREAD

**Issue by shaddu** [Wikiki/bulma-quickview#14]
I am trying to use bulmaQuick in a react project & I am having issue with using below reference 
`<script type="text/javascript" src="/node_modules/bulma-extensions/bulma-quickview/dist/bulma-quickview.min.js"></script>` .

The issue is that my production build is ignoring the node modules to be bundled, so how should I add the reference to `bulma.quickview.min.js`

**Comment by emanur** [comment]
You have a build problem, not a Quickview problem.

**Comment by Wikiki** [comment]
closed due to inactivity
