### ISSUE TITLE
Mobile display doesn't have the 'delete' button

### ISSUE THREAD

**Issue by sausin** [Wikiki/bulma-quickview#2]
Hi Wikiki,

As always, thanks for your amazing work on bulma! I think there may be an issue with the quickview extension.

It is reproducible on the extensions overview [page](https://wikiki.github.io/bulma-extensions/quickview).

Change to mobile view and activate the quickview. The delete button is not accessible.

It would be awesome if this could be fixed!

Thanks,
Saurabh

**Comment by Wikiki** [comment]
Hi sausin,

It seems to be a browser's bug. It's perfectly working on Firefox but on Chrome it seems that the quickview's still using the screen resolution instead of the mobile preview size.

I'll try to fix it.

Regards

**Comment by Wikiki** [comment]
Fixed.

The error was due to an issue in doc an not in the extension.

Sorry about that.

**Comment by sausin** [comment]
@Wikiki thanks, it works perfectly now!
