### ISSUE TITLE
Typo in package.json, bulma-quickview.min.jss

### ISSUE THREAD

**Issue by frankwaalkens** [Wikiki/bulma-quickview#26]
![image](https://user-images.githubusercontent.com/11975073/63950359-1f378b00-ca7c-11e9-9ab0-392a0c888006.png)

**Comment by Wikiki** [comment]
already fixed

**Comment by BobbieBarker** [comment]
The problem isn't really fixed if you don't publish the solution.

**Comment by gentilmente** [comment]
this is still an issue
