### ISSUE TITLE
Use as Side Drawer for Hamburger Menu?

### ISSUE THREAD

**Issue by kerbo** [Wikiki/bulma-quickview#27]
I'm trying to use quickview as a side drawer when the hamburger menu item is clicked. The drawer will open and close when the hamburger is clicked.

The problem is the height of quickview window covers the entire viewport including the navbar and here is no way to close the window since the hamburger is covered.

Is there any way to adjust the height of the window so it doesn't cover the navbar?

**Comment by Wikiki** [comment]
Hi,

The quickview component is made to be full-height.
You can add a custom CSS to add a top margin.

regards
