### ISSUE TITLE
issue with scroll

### ISSUE THREAD

**Issue by bcarneiro** [Wikiki/bulma-quickview#3]
Just looked at this extension, and I've noticed an issue with the scroll. 

Adding scroll to that section, would created that problem of double scroll. 
Maybe it should add the class .is-clipped to the html tag, and it should be able to scroll the specific content. 
To complete this behave, maybe add a background like the modal.

I can really see this a side navigation for most websites.

**Comment by Wikiki** [comment]
Hi,

Can you please elaborate your idea ?
I don't see any way to manage all possible layouts by just adding <code>is-clipped</code> to HTML tag.

Regards

**Comment by talismax** [comment]
FYI, I don't really know what I'm doing with CSS but I was able to get the quickview content to scroll vertically by adding these to the .quickview class:

overflow-y: auto
overflow-x: hidden
max-height: 100vh

**Comment by Wikiki** [comment]
hi,

overflow-y: auto is good but max-height: 100vh is to avoid otherwise you will not be able to have lots of content inside the quickview-body.

I've added overflow-y: auto. Give it a try and tell me if it's ok in your context.

**Comment by Wikiki** [comment]
Sorry I read quickview-body instead of .quickview.

Can you please tell me which browser and OS you are using ?
And provide a screenshot of the double scroll you have ?

**Comment by Wikiki** [comment]
Closed due no-activity.
