### ISSUE TITLE
Left hand quickview

### ISSUE THREAD

**Issue by GrizzlyEnglish** [Wikiki/bulma-quickview#38]
Would be nice to have a left handed quickview modifier.

**Comment by francesco-loreti** [comment]
> Would be nice to have a left handed quickview modifier.
Hi, this option already exists. 
If you add `is-left` to `quickview`, the menu switches to the left.

**Comment by GrizzlyEnglish** [comment]
@francesco-loreti Oh, thank you. Apologies. Clearly I did not look at all before making this.
